### Embeddings de sentença e clusters

In [ ]:
!pip install -q gdown

import pandas as pd
import gdown

file_id = '1ZyTlST3HpdvW0db_Yl8Im8EL9YoLl3GU'
output_path = 'df.csv'

gdown.download(id=file_id, output=output_path, quiet=False)

df = pd.read_csv(output_path, delimiter='|', quotechar='"')

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "sentence-transformers/all-mpnet-base-v2"
)

emails = df["reprocessed_text"].astype(str).tolist()

embeddings2 = model.encode(
    emails,
    show_progress_bar=True
)

df["transformer_embeddings2"] = pd.Series(list(embeddings2))

In [ ]:
import umap
import hdbscan

reducer = umap.UMAP(
    n_components=20,
    n_neighbors=15,
    min_dist=0
)

X_red = reducer.fit_transform(embeddings2)

clusterer = hdbscan.HDBSCAN(
    min_cluster_size=10
)

df['clusters2'] = clusterer.fit_predict(X_red)

### Arquivo já processado

In [1]:
!pip install -q gdown

import pandas as pd
import gdown

file_id = '1CsOmkiFuvrtFNBSK_mZFQjgBuFx89Rht'
output_path = 'df.csv'

gdown.download(id=file_id, output=output_path, quiet=False)

df = pd.read_parquet(output_path)

Downloading...
From (original): https://drive.google.com/uc?id=1CsOmkiFuvrtFNBSK_mZFQjgBuFx89Rht
From (redirected): https://drive.google.com/uc?id=1CsOmkiFuvrtFNBSK_mZFQjgBuFx89Rht&confirm=t&uuid=669890a7-a8bf-44bd-abec-0aedfc7651ed
To: /content/df.csv
100%|██████████| 772M/772M [00:12<00:00, 62.4MB/s]

In [4]:
df = df[df.clusters != -1]

In [5]:
from sklearn.model_selection import train_test_split
if 'clusters' in df.columns and len(df['clusters'].unique()) > 1:
    df_sample, _ = train_test_split(df, test_size=0.9, stratify=df['clusters'], random_state=42)
    print(f"Original DataFrame size: {len(df)}")
    print(f"Sampled DataFrame size: {len(df_sample)}")
    print("Stratified sample head:")
    display(df_sample.head())
else:
    df_sample = df.sample(frac=0.1, random_state=42)
    display(df_sample.head())

Original DataFrame size: 50332
Sampled DataFrame size: 5033
Stratified sample head:

,file,content,email_content,preprocessed_text,count_tokens,count_misspellings,count_sentences,NER,doc2vec,transformer_embeddings,clusters,reprocessed_text,transformer_embeddings2
19692,EFTA01683762.pdf,"From:\nSubject:\nTo:\nCc:\nSent: ugust 11, 202...",Classification: SECRET\nClassified By:\nDerive...,classification secret classified derive declas...,85.0,10.0,1.0,"{""company"": [""search bureau"", ""fbi""], ""person""...",-0.021562135,"[0.036078144, 0.12062369, -0.023542676, 0.0157...",209,classification secret classified derive declas...,"[0.036078144, 0.12062369, -0.023542676, 0.0157..."
64243,EFTA01826048.pdf,To: Vera\nFrom: Jeffrey Epste\nSent Sat 3/6/20...,"Dear Jeffrey\nThank you very much for tonight,...",dear jeffrey thank tonight wonderful special a...,46.0,0.0,1.0,"{""company"": [], ""person"": [""jeffrey epstein"", ...",0.016047081,"[0.051212884, 0.06553941, 0.0006131679, 0.0458...",942,dear jeffrey thank tonight wonderful special a...,"[0.051212903, 0.06553942, 0.0006131472, 0.0458..."
2458,EFTA00024413.pdf,"From:\nTo: 'Moyne, Parvin'\nCc:\n'Moyer, Thoma...",&\nPlease find attached an index to our produc...,find attach index production date work progres...,94.0,9.0,1.0,"{'company': ['alsgialp com'], 'person': [], 'l...",0.0019033913,"[0.059096284, 0.03989319, 0.012785217, -0.0248...",221,find attach index production work progress upd...,"[0.052581165, 0.052050576, 0.01264816, -0.0176..."
56894,EFTA01814126.pdf,To: Daniel Siad(\nFrom: Jeffrey Epstein\nSent ...,Hello Jeffrey\ntry to call me or email me to l...,hello jeffrey try email let know solution come...,94.0,2.0,3.0,"{""company"": [""rcgard""], ""person"": [""jeffrey"", ...",0.024137393,"[0.053532638, 0.056572665, 0.017525822, 0.0511...",945,hello jeffrey try email let know solution come...,"[0.053532638, 0.056572665, 0.017525822, 0.0511..."
42011,EFTA01781971.pdf,"From:\nSent: Friday, August 12, 2016 11:23 PM\...",The Jojo thing is a tricky one but I don't kno...,jojo thing tricky know lean yes stay crazy har...,61.0,6.0,1.0,"{""company"": [""team""], ""person"": [""jojo"", ""mans...",-0.014449115,"[0.05164791, 0.06735403, 0.009353169, -0.01701...",869,jojo thing tricky know lean yes stay crazy har...,"[0.05164791, 0.06735403, 0.009353169, -0.01701..."

In [ ]:
df_sample

,file,content,email_content,preprocessed_text,count_tokens,count_misspellings,count_sentences,NER,doc2vec,transformer_embeddings,clusters,reprocessed_text,transformer_embeddings2
65549,EFTA01828056.pdf,To:\nFrom: Jeevacation\nSent Mon 12/6/2010 10:...,Last summer was amazing and I learned an incre...,summer amazing learn incredible new informatio...,36.0,1.0,2.0,"{""company"": [], ""person"": [], ""location"": [], ...",-0.0067339856,"[0.012992536, 0.042431086, 0.005102642, -0.041...",1014,summer amazing learn incredible new informatio...,"[0.012992576, 0.04243106, 0.00510261, -0.04103..."
39236,EFTA01776342.pdf,"From: `M >\nSent: Friday, September 9, 2011 8:...","Hi Jeffrey,\nI had my first class this morning...",hi jeffrey class morning teacher richard great...,25.0,4.0,1.0,"{""company"": [], ""person"": [], ""location"": [], ...",0.011320753,"[-0.030552743, -0.04563656, -0.050633058, -0.0...",-1,hi jeffrey class morning teacher richard great...,"[-0.030552614, -0.04563647, -0.050633, -0.0422..."
70804,EFTA01837022.pdf,To: Lesley Grol\nFran: Jeffrey Epstein\nSent M...,Do you want to speak with Bill Elkus at 6:30 E...,want speak bill elkus east coast time today sh...,59.0,2.0,1.0,"{""company"": [], ""person"": [""bill elkus"", ""jeff...",0.028948508,"[0.03574109, 0.10902244, 0.0060844608, 0.04910...",-1,want speak bill elkus east coast time today sh...,"[0.03574109, 0.10902244, 0.0060844608, 0.04910..."
68034,EFTA01832141.pdf,To: ' v tin mail.com[jeeyacation@gmail.com]\nF...,Are you coming to town?\nEFTA_R1_00209682\n,come town,2.0,0.0,1.0,"{""company"": [], ""person"": [], ""location"": [], ...",0.023496363,"[-0.069248036, 0.07549728, 0.006734119, 0.0273...",-1,come town,"[-0.069248006, 0.0754973, 0.006734142, 0.02737..."
5300,EFTA00038876.pdf,From:\nTo:\nCc:\nSubject: Re: FOIA requests th...,The FAA has previously received FOIA requests ...,faa previously receive foia request seek histo...,95.0,4.0,1.0,"{'company': ['faa', 'fbi', 'business insider',...",-0.029321535,"[0.012188172, 0.12738433, -0.037822153, 0.0142...",-1,faa previously receive foia request seek histo...,"[0.012188172, 0.12738433, -0.037822153, 0.0142..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87690,EFTA01867948.pdf,To: Daniel Siad\nFran: Jeffrey Epstein\nSent W...,Fran: Jeffrey Epstein\nSent Wed 6/1/2011 7:59:...,fran jeffrey epstein send pm phone anwcr infor...,49.0,1.0,1.0,None,0.03338414,"[0.046872478, 0.08680047, -0.0060747275, 0.043...",194,fran jeffrey epstein send pm phone anwcr infor...,"[0.046872504, 0.08680047, -0.0060747517, 0.043..."
35186,EFTA01768475.pdf,From: Jeffrey <jeevacation@gmail.com>\nSent: S...,"Making reservation , cranky , priorty conversa...",make reservation cranky priorty conversation s...,26.0,6.0,1.0,"{""company"": [], ""person"": [], ""location"": [], ...",0.038712904,"[0.04349152, -0.020887315, 0.0057631205, 0.017...",247,make reservation cranky priorty conversation s...,"[0.05535343, -0.015154076, -0.015752137, 0.054..."
68349,EFTA01832675.pdf,To:\nFrom: Jeffrey Epstein\nSent Thur 12/30/20...,I wish I could see you soon miss you all kiss\...,wish soon miss kiss send iphone information co...,50.0,1.0,1.0,"{""company"": [""iphone""], ""person"": [""jeffrey ep...",0.03173109,"[0.08343244, 0.06391185, -0.01776557, 0.008196...",416,wish soon miss kiss send iphone information co...,"[0.083432406, 0.063911855, -0.017765595, 0.008..."
42141,EFTA01782271.pdf,From: New York Junior Tennis & Learning\nSent:...,<http://img.constantcontact.com/letters/=mages...,nyjtl uniqlo bringthelove dear nyjtl family ny...,165.0,27.0,1.0,"{""company"": [""nyjtl uniqlo"", ""ssion grow game ...",0.0006141629,"[-0.003765125, 0.04634368, -0.0017047401, 0.04...",-1,nyjtl uniqlo bringthelove dear nyjtl family ny...,"[-0.003765125, 0.04634368, -0.0017047401, 0.04..."
21841,EFTA01739373.pdf,"From:\nSubject: rancis er y\nSent: Friday, Oct...",So Francis said he'd be in LA from the 7-20th ...,francis say la excited hear interested meeting...,9.0,0.0,1.0,"{""company"": [], ""person"": [], ""location"": [], ...",0.00039090615,"[0.024029896, 0.07183514, -0.017738786, 0.0495...",-1,francis say la excited hear interested meeting...,"[0.024029896, 0.07183514, -0.017738786, 0.0495..."

In [ ]:
df_sample.clusters.value_counts().head(10)

clusters
242     188
828     140
236      77
194      69
254      68
942      62
88       51
1027     42
1125     42
898      36
Name: count, dtype: int64

In [ ]:
df_sample_filt = df_sample[df_sample.clusters.isin([828, 236, 194, 254, 942, 88, 1125])]

In [ ]:
import numpy as np
embeddings_array = np.array(df_sample_filt['transformer_embeddings2'].tolist())

print(f"Shape of the embeddings array: {embeddings_array.shape}")
print("First 5 rows of the transformed array:")
display(embeddings_array[:5])

Shape of the embeddings array: (509, 768)
First 5 rows of the transformed array:

array([[ 0.0512129 ,  0.06553942,  0.00061315, ..., -0.01799077,
        -0.02367971,  0.00684386],
       [ 0.04533633,  0.08580007,  0.00326648, ..., -0.01040771,
        -0.00722546, -0.02898328],
       [ 0.03247374,  0.1077615 ,  0.01209256, ..., -0.01118065,
        -0.04652897, -0.0172168 ],
       [ 0.08520442,  0.06325795, -0.00645814, ..., -0.04205715,
        -0.03966954, -0.00249079],
       [ 0.01204174, -0.02836518,  0.01029554, ..., -0.0098633 ,
        -0.04751444,  0.01918472]], dtype=float32)

In [ ]:
!pip install -q umap-learn

In [ ]:
# @title Gráfico de Clusters
import umap
import plotly.express as px
import pandas as pd

umap_reducer = umap.UMAP(n_components=3, random_state=42, n_jobs=1)

umap_components = umap_reducer.fit_transform(embeddings_array)

umap_df = pd.DataFrame(data=umap_components, columns=['UMAP1', 'UMAP2', 'UMAP3'])

if 'clusters' in df_sample_filt.columns and len(df_sample_filt['clusters'].unique()) > 1:
    umap_df['Cluster'] = df_sample_filt['clusters'].astype(str).values
    fig = px.scatter_3d(umap_df, x='UMAP1', y='UMAP2', z='UMAP3', color='Cluster',
                        title='UMAP dos Embeddings',
                        labels={'UMAP1': 'Component 1', 'UMAP2': 'Component 2', 'UMAP3': 'Component 3'})
else:
    fig = px.scatter_3d(umap_df, x='UMAP1', y='UMAP2', z='UMAP3',
                        title='UMAP dos Embeddings',
                        labels={'UMAP1': 'UMAP Component 1', 'UMAP2': 'UMAP Component 2', 'UMAP3': 'UMAP Component 3'})

fig.show()

In [ ]:
df_sample_filt[df_sample_filt.clusters == 88].reprocessed_text.head(5)

16284    harry heber april jege account wire dollars ac...
17237    harry beller september morgan account wire dol...
17094    harry october jeffrey stein account wire dolla...
15216    harry defier october jeffrey epsteili account ...
16748    harry beller july jp mo account wire dollar ac...
Name: reprocessed_text, dtype: object

In [ ]:
df_sample_filt[df_sample_filt.clusters == 236].reprocessed_text.head(5)

53802    attachment untitled attachment untitled attach...
30691    attachment photojpg untitled attachment imagej...
29845    attachment photo untitled attachment photo unt...
5299                               attachment black attach
30188                                  attachment photojpg
Name: reprocessed_text, dtype: object

### Avaliação NER

In [6]:
import json
from collections import Counter

company_entities = Counter()
person_entities = Counter()
location_entities = Counter()
travel_location_entities = Counter()


for ner_entry in df['NER']:
    if pd.isna(ner_entry) or ner_entry == '{}':
        continue
    try:
        ner_data = json.loads(ner_entry)
        for entity_type, entities_list in ner_data.items():
            for entity in entities_list:
                if entity_type == 'company':
                    company_entities[entity.lower()] += 1
                elif entity_type == 'person':
                    person_entities[entity.lower()] += 1
                elif entity_type == 'location':
                    location_entities[entity.lower()] += 1
                elif entity_type == 'travel_location':
                    travel_location_entities[entity.lower()] += 1
    except json.JSONDecodeError:
        #print(f"Could not decode JSON: {ner_entry}")
        continue

print("\nTop most common Company Entities:")
for entity, count in company_entities.most_common(20):
    print(f"- {entity}: {count}")

print("\nTop most common Person Entities:")
for entity, count in person_entities.most_common(20):
    print(f"- {entity}: {count}")

print("\nTop most common Location Entities:")
for entity, count in location_entities.most_common(20):
    print(f"- {entity}: {count}")

print("\nTop most common Travel Location Entities:")
for entity, count in travel_location_entities.most_common(20):
    print(f"- {entity}: {count}")

Top most common Company Entities:
- db: 2755
- deutsche bank: 2257
- southern financial llc: 1923
- southern trust company inc: 916
- fbi: 859
- db group: 746
- deutsche bank group: 676
- iphone: 637
- jege llc: 589
- hyperion air llc: 557
- jege inc: 551
- blackberry: 535
- deutsche bank group db: 516
- gmail: 481
- hbrk associates inc: 454
- nes llc: 411
- neptune llc: 404
- usd: 391
- hyperion air inc: 361
- deutsche bank ag: 348

Top most common Person Entities:
- jeffrey epstein: 30708
- attorney client: 4605
- jeffrey: 2837
- epstein: 1307
- sender: 1168
- paul morris: 949
- recipient: 885
- fran jeffrey epstein: 687
- harry beller: 531
- amanda kirby: 503
- tazia smith: 442
- richard kahn: 408
- daniel sabba: 402
- larry: 335
- ariane dwyer: 310
- darren indyke pllc: 291
- edmond de rothschild: 282
- effrey epstein: 260
- karen wanek: 250
- richard: 246

Top most common Location Entities:
- new york: 1490
- paris: 1006
- new york ny: 874
- london: 667
- ny: 312
- nyc: 302
- israel: 279
- china: 248
- park avenue: 248
- europe: 235
- dubai: 234
- england: 224
- florida: 200
- uk: 180
- miami: 175
- canada: 167
- palm beach: 148
- united states: 146
- russia: 129
- park avenue new york ny: 127

Top most common Travel Location Entities:
- paris: 567
- new york: 417
- london: 218
- usa: 181
- dubai: 170
- new york ny: 157
- nyc: 145
- miami: 143
- ny: 128
- israel: 125
- united states: 110
- europe: 108
- florida: 100
- france: 76
- china: 62
- jeevacation: 56
- canada: 52
- airport: 52
- russia: 46
- palm beach: 44